### ISSUE TITLE
[BUG]: Can only concatenate str not numpy.float64

### ISSUE THREAD

**Issue by abhinavvittal** [NLP-Suite/NLP-Suite#1159] opened 2023-09-16 16:58 UTC
**Add a screenshot of the GUI you are running with the widget selections**

**Describe the bug**
For HW4, when I try running the parser, the program quits and in terminal I get this error:

TypeError: can only concatenate str (not "numpy.float64") to str
Traceback (most recent call last):
  File "parsers_annotators_main.py", line 699, in <module>
    activate_NLP_options()
  File "parsers_annotators_main.py", line 668, in activate_NLP_options
    available_parsers = 'Parsers for ' + package # + '                          '
TypeError: can only concatenate str (not "numpy.float64") to str

**To Reproduce**
1. Open NLP Suits
2. Go to CORPUS/DOCUMENT Analysis Tools
3. Select "Parsers and annotators (BERT, CoreNLP, spaCy, Stanza)
4. Click run

**Screenshots**
<img width="1328" alt="Screenshot 2023-09-16 at 12 58 00 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/78614674/5f275a23-55e8-4749-9d44-5803ce591e94">

<img width="557" alt="Screenshot 2023-09-16 at 12 58 22 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/78614674/47fd06dd-f32f-4b5b-914d-13f173bef2ad">

**Desktop (please complete the following information):**
 - OS: OSX
 - Release Version: type `NLP -- 3.9.7

**Additional context**
Using HIV Corpus

**Comment by bianshuyang** [comment] 2023-09-16 20:22
[NLP_default_package_language_config.csv](https://github.com/NLP-Suite/NLP-Suite/files/12641517/NLP_default_package_language_config.csv)
Hi, What is your `NLP_default_package_language_config.csv` like in the config folder? Would you be able to replace it with another one and see if it works?

**Comment by bianshuyang** [comment] 2023-09-16 20:23
Also, paste an image of the config file and show what it looks like.
Mine is like:
![image](https://github.com/NLP-Suite/NLP-Suite/assets/52821055/dfacffb5-02de-4f9d-8d0b-f4938fedd370)

**Comment by abhinavvittal** [comment] 2023-09-16 20:50
Hi Simon,

I attached my config file. When I replaced it with yours, I got "key error: 'myv' in terminal. I have attached a picture.

[https://res.cdn.office.net/assets/mail/file-icon/png/csv_16x16.png]NLP_default_package_language_config.csv<https://emory-my.sharepoint.com/:x:/g/personal/avittal_emory_edu/EZ_5CL_3j69GqvtPKo0ACZABOrBm4uVykmBJ3eAAzeoixQ>

Best,
Nav
________________________________
From: Shuyang Bian ***@***.***>
Sent: Saturday, September 16, 2023 4:22 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Vittal, Abhinav ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Can only concatenate str not numpy.float64 (Issue #1159)


NLP_default_package_language_config.csv<https://github.com/NLP-Suite/NLP-Suite/files/12641517/NLP_default_package_language_config.csv>
Hi, What is your NLP_default_package_language_config.csv like in the config folder? Would you be able to replace it with another one and see if it works?

**Comment by bianshuyang** [comment] 2023-09-18 17:45
I am closing this issue and transfers it to the main thread. This is a duplicate of: https://github.com/NLP-Suite/NLP-Suite/issues/1160
You must see my comments at the end.

**Comment by bianshuyang** [comment] 2023-09-18 17:46
myv means something wrong with the version of Stanza, which you must **downgrade**.

**Closed as completed by bianshuyang** 2023-09-18 17:45 UTC
Labels: bug, student-bug
