### ISSUE TITLE
ISSUE IN OPENING NLP SUITE

### ISSUE THREAD

**Issue by avarnaswaika** [NLP-Suite/NLP-Suite#353] opened 2021-09-09 20:14 UTC
**Describe the bug**
While trying to open the GitHub software, an error shows that we do not have access to it. 

**To Reproduce**
1. Go to NLP run command in Mac 

**Screenshots**
<img width="736" alt="123" src="https://user-images.githubusercontent.com/89501720/132756064-3013a0e5-7b75-4bf1-ac77-a1119fc1e867.png">

**Desktop (please complete the following information):**
 - OS:

**Comment by DDVD233** [comment] 2021-09-10 00:23
Please try updating to the latest release and see if that solves the problem.

**Comment by RafaelPiloto10** [comment] 2021-09-10 17:47
Duplicate of #354, closing. Please follow #354 for updates. If the latest release did not fix your issue, please reopen this issue and tag @DDavid233  or @RafaelPiloto10.

**Closed as completed by RafaelPiloto10** 2021-09-10 17:47 UTC
Labels: bug, student-bug
