### ISSUE TITLE
[BUG]: CoNLL table analysis via the Style Analysis GUI is failing

### ISSUE THREAD

**Issue by zoneli13** [NLP-Suite/NLP-Suite#277] opened 2021-04-24 23:33 UTC
**Describe the bug**
We are using the Motley Fool corpus we compiled. We input the CoNLL table as the input file and selected CoNLL table Analysis. We tried both 'Function words' and 'Verbs', and the end result was the same error.

**To Reproduce**
1. Go to 'CORPUS/DOCUMENT Analysis Tools'
2. Click on 'Style Analysis'
3. Input a CoNLL table as the INPUT file
4. Check CoNLL table Analysis and scroll to 'Function words' or 'Verbs'
5. See error after processing
<img width="1424" alt="Screen Shot 2021-04-24 at 7 31 10 PM" src="https://user-images.githubusercontent.com/44302000/115975537-a2500380-a533-11eb-8982-bf77b519062d.png">

**Screenshots**
Add screenshots to help explain your problem and indicate the error.

**Desktop (please complete the following information):**
 - OS: Mac OSX Catalina
 - NLP 1.3.8

**Additional context**

**Comment by Emory-NLP** [comment] 2021-04-25 02:51
Could you send me the input cnnll table for testing? Thanks!

Roberto
Sent from my iPhone

On Apr 24, 2021, at 7:33 PM, zoneli13 ***@***.***> wrote:

﻿

Describe the bug
We are using the Motley Fool corpus we compiled. We input the CoNLL table as the input file and selected CoNLL table Analysis. We tried both 'Function words' and 'Verbs', and the end result was the same error.

To Reproduce
Steps to reproduce the behavior:

  1.  Go to 'CORPUS/DOCUMENT Analysis Tools'
  2.  Click on 'Style Analysis'
  3.  Input a CoNLL table as the INPUT file
  4.  Check CoNLL table Analysis and scroll to 'Function words' or 'Verbs'
  5.  See error after processing

[Screen Shot 2021-04-24 at 7 31 10 PM]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F44302000%2F115975537-a2500380-a533-11eb-8982-bf77b519062d.png&data=04%7C01%7Crfranzo%40emory.edu%7C9c28c09de0d34fab84ac08d907795ccf%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637549040109680761%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7KDnK6lEjxOky%2FpW6WFlceNWdH%2F%2FgYWJiDHpQqxJt3w%3D&reserved=0>

Screenshots
Add screenshots to help explain your problem and indicate the error.

Desktop (please complete the following information):

  *   OS: Mac OSX Catalina
  *   NLP 1.3.8

Additional context
Add any other context about the problem here.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F277&data=04%7C01%7Crfranzo%40emory.edu%7C9c28c09de0d34fab84ac08d907795ccf%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637549040109690754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tjfwYalLcVPss6HuS3KHf4cc8QRZb94dMfl4MvaOP0Y%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q52D5JWDU4EOYGWXZITTKNIMPANCNFSM43QUFJFA&data=04%7C01%7Crfranzo%40emory.edu%7C9c28c09de0d34fab84ac08d907795ccf%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637549040109690754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7jvFMQ6UP8JwQHpJm9ZRv45L%2FelF4orrooWDFCmslko%3D&reserved=0>.

________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).

**Comment by zoneli13** [comment] 2021-04-25 15:54
Here is the CoNLL table we used. 
[NLP_CoreNLP_Dir_2020dataFinal_CoNLL.csv.zip](https://github.com/NLP-Suite/NLP-Suite/files/6372335/NLP_CoreNLP_Dir_2020dataFinal_CoNLL.csv.zip)

Thank you!

**Comment by Emory-NLP** [comment] 2021-04-25 17:50
Thank you. Will test

From: zoneli13 ***@***.***>
Sent: Sunday, April 25, 2021 11:54 AM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: CoNLL table analysis via the Style Analysis GUI is failing (#277)


Here is the CoNLL table we used.
NLP_CoreNLP_Dir_2020dataFinal_CoNLL.csv.zip<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Ffiles%2F6372335%2FNLP_CoreNLP_Dir_2020dataFinal_CoNLL.csv.zip&data=04%7C01%7Crfranzo%40emory.edu%7Ce1ecae8bb2e94e4c8c3608d908026752%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637549628680505170%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=D7sKQ9mwn5mOU0kyWoHVh56EbvbugCfeUtbnCasFgj0%3D&reserved=0>

Thank you!

-
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F277%23issuecomment-826346476&data=04%7C01%7Crfranzo%40emory.edu%7Ce1ecae8bb2e94e4c8c3608d908026752%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637549628680505170%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jPnkuydF8VeqzRvzxgaSVZbRxLWJuUmVEB8lxKrAcCQ%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q5YIJ2NVL6PQ5YS5SI3TKQ3LDANCNFSM43QUFJFA&data=04%7C01%7Crfranzo%40emory.edu%7Ce1ecae8bb2e94e4c8c3608d908026752%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637549628680515165%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tF%2F4QEj2e2CDZl9QMsUIqsyJxzZMvp%2FAg09oIeYsOJo%3D&reserved=0>.

________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).

**Comment by Emory-NLP** [comment] 2021-04-25 17:53
As I suspected, and as mentioned in class, the CoNLL table you are using was generated with a Record ID that restarted from 1 with every new document. It was a bug that Claude subsequently fixed. You need to run the parser again.

From: zoneli13 ***@***.***>
Sent: Sunday, April 25, 2021 11:54 AM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: CoNLL table analysis via the Style Analysis GUI is failing (#277)


Here is the CoNLL table we used.
NLP_CoreNLP_Dir_2020dataFinal_CoNLL.csv.zip<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Ffiles%2F6372335%2FNLP_CoreNLP_Dir_2020dataFinal_CoNLL.csv.zip&data=04%7C01%7Crfranzo%40emory.edu%7Ce1ecae8bb2e94e4c8c3608d908026752%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637549628680505170%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=D7sKQ9mwn5mOU0kyWoHVh56EbvbugCfeUtbnCasFgj0%3D&reserved=0>

Thank you!

-
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F277%23issuecomment-826346476&data=04%7C01%7Crfranzo%40emory.edu%7Ce1ecae8bb2e94e4c8c3608d908026752%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637549628680505170%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jPnkuydF8VeqzRvzxgaSVZbRxLWJuUmVEB8lxKrAcCQ%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q5YIJ2NVL6PQ5YS5SI3TKQ3LDANCNFSM43QUFJFA&data=04%7C01%7Crfranzo%40emory.edu%7Ce1ecae8bb2e94e4c8c3608d908026752%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637549628680515165%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tF%2F4QEj2e2CDZl9QMsUIqsyJxzZMvp%2FAg09oIeYsOJo%3D&reserved=0>.

________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).

**Comment by zoneli13** [comment] 2021-04-26 03:52
I ran our corpus through the parser again to get the new CoNLL table. Then I ran the same 'Function words'  style analysis as above. I got this error.
<img width="1144" alt="Screen Shot 2021-04-25 at 11 49 46 PM" src="https://user-images.githubusercontent.com/44302000/116026525-ee2ca680-a620-11eb-9593-d934d2bbc616.png">
Here is the CoNLL table.
[NLP_CoreNLP_Dir_2020dataFinal_CoNLL.csv.zip](https://github.com/NLP-Suite/NLP-Suite/files/6374169/NLP_CoreNLP_Dir_2020dataFinal_CoNLL.csv.zip)

Thank you!

**Comment by Emory-NLP** [comment] 2021-04-26 12:56
Bug fixed in 1.4.0. We no longer export line charts given errors in the script but the CoNLL table analysis in the GUI still exported line charts.

**Comment by Emory-NLP** [comment] 2021-04-26 12:57
Bug fixed in 1.4.0. We no longer export line charts given errors in the script but the CoNLL table analysis in the GUI still exported line charts.

**Closed as completed** 2021-04-26 12:57 UTC
Labels: bug, student-bug
